language: python
python:
  - 3.6.5
install:
  - pip install -r requirements.txt
  # - pip install coveralls

script:
  - python --cov=.
  - coverage
  - coveralls
  - coverage report

after_success:
  - coveralls

notifications:
  emails:false
  