language: python

python:
    - 2.7
    - 3.5
    - 3.6
# install dependencies
before_script:
  - pip install -r requirements.txt

before_script:
  - easy_install distribute
  - pip install -r requirements.txt