language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - FLASK=1.0.2
matrix:
  exclude:
    - python: "3.6"
      env: FLASK=1.0.2
install:
  - pip install flask==$FLASK coverage
  - pip install -e .
script:
  - python run.py test
notifications:
  email:
    - dwabuluka@gmail.com
